name: CI JOBS

on: push

jobs:
  job1:
    runs-on: centos-latest
    steps:
      - name: print calendar
        run: cal
      - name: print date
        run: date

  job2:
    runs-on: macos-latest
    steps:
      - name: print calendar
        run: cal
      - name: print date
        run: date

  job3:
    runs-on: windows-latest
    steps:
      - name: print date
        run: Get-Date
